language: php
sudo: required
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - master
env:
  - 'PHPUNIT=true'

before_install:
- sudo apt-get update -qq
- sudo apt-get install -y php5-sqlite

before_script:
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-dist

script:
- vendor/bin/phpunit --configuration phpunit.xml.dist tests

after_success:
- bash <(curl -s https://codecov.io/bash)
