language: php
sudo: required
php:
- '5.6'
- '5.7'
- '7.0'
- '7.1'
- '7.2'

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq php-sqlite3

before_script:
- travis_retry composer self-update
- travis_retry composer install --no-interaction --prefer-source --dev

script:
- vendor/bin/phpunit --connfiguration phpunit.xml tests --teamcity

after_success:
- bash <(curl -s https://codecov.io/bash)