<?php
/**
 * This file contains the definition for the DataTransaction class
 *
 * @author Ryan Howe
 * @since  2018-10-12
 */

namespace Test;

use Doctrine\DBAL\Configuration;
use Doctrine\DBAL\DriverManager;
use PHPUnit\Framework\TestCase;
use ryanwhowe\KeyValueStore\Manager;

class DataTransaction extends TestCase {
    /**
     * @var \Doctrine\DBAL\Connection
     */
    protected static $connection;

    /**
     * @var array The local SQLite memory database connection configuration array
     */
    protected static $database_config = [
        'dbname' => ':memory:',
        'host'   => 'localhost',
        'driver' => 'pdo_sqlite',
    ];

    /**
     * @throws \Doctrine\DBAL\DBALException
     */
    public static function setUpBeforeClass()
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        self::$connection = DriverManager::getConnection(self::$database_config, new Configuration());
    }

    /**
     * This is the setUp method, this will create the testing database connected to a local SQLite instanced in
     * memory, there should be no residual tables or test data to clean up from this class.
     *
     * @throws \Doctrine\DBAL\DBALException
     */
    protected function setUp()
    {
        Manager::create(self::$connection)->createTable();
    }

    /**
     * This is the teardown method for the testing class.  All cleanup operations should be performed here.
     *
     * @throws \Doctrine\DBAL\DBALException
     */
    protected function tearDown()
    {
        Manager::create(self::$connection)->dropTable();
    }
}