<?php
/**
 * This file contains
 *
 * @author Ryan Howe
 * @since  2018-10-12
 */

namespace Test;

use Doctrine\DBAL\Configuration;
use Doctrine\DBAL\DriverManager;
use ryanwhowe\KeyValueStore\Manager;

class ManagerTest extends \PHPUnit\Framework\TestCase {

    /**
     * @var \Doctrine\DBAL\Connection
     */
    protected static $connection;

    /**
     * @var array The local SQLite memory database connection configuration array
     */
    protected static $database_config = array(
        'dbname' => ':memory:',
        'host'   => 'localhost',
        'driver' => 'pdo_sqlite',
    );

    /**
     * @throws \Doctrine\DBAL\DBALException
     */
    public static function setUpBeforeClass()
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        self::$connection = DriverManager::getConnection(self::$database_config, new Configuration());
    }

    public function testCreate()
    {
        $test = Manager::create(self::$connection);
        $this->assertInstanceOf('ryanwhowe\KeyValueStore\Manager', $test);
    }

    public function testCreateTable()
    {
        $test = Manager::create(self::$connection);
        $test->createTable();
        $sql = "SELECT name FROM sqlite_master WHERE type='table' AND name='ValueStore';";
        $result = self::$connection->executeQuery($sql)->fetch(\PDO::FETCH_COLUMN);
        $test->dropTable();
        $this->assertEquals('ValueStore', $result);
    }

    /**
     * @throws \Exception
     */
    public function testGetAllGroupings()
    {
        $test = Manager::create(self::$connection);
        $test->createTable();
        $expected = array();
        $singleValue = \ryanwhowe\KeyValueStore\Store\SingleValue::create('Test1', self::$connection);
        $expected[] = 'Test1';
        $singleValue->set('Key', 'Value');
        $singleValue = \ryanwhowe\KeyValueStore\Store\SingleValue::create('Test2', self::$connection);
        $expected[] = 'Test2';
        $singleValue->set('Key', 'Value');
        $singleValue = \ryanwhowe\KeyValueStore\Store\SingleValue::create('Test3', self::$connection);
        $expected[] = 'Test3';
        $singleValue->set('Key', 'Value');
        $result = $test->getAllGroupings();
        $test->dropTable();
        $this->assertEquals($expected, $result);
    }

    public function testDropTable()
    {
        $test = Manager::create(self::$connection);
        $test->createTable();
        $sql = "SELECT name FROM sqlite_master WHERE type='table' AND name='ValueStore';";
        $test->dropTable();
        $result = self::$connection->executeQuery($sql)->fetch(\PDO::FETCH_COLUMN);
        $this->assertEquals(false, $result);
    }

}
